"""Add replies table

Revision ID: c34df6d933d0
Revises: 8813bec613c1
Create Date: 2026-03-13 09:38:54.927292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34df6d933d0'
down_revision: Union[str, None] = '8813bec613c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outreach_message_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('provider_thread_id', sa.String(), nullable=True),
    sa.Column('reply_text', sa.String(), nullable=True),
    sa.Column('classification', sa.Enum('interested', 'not_interested', 'ask_later', 'bounced', 'out_of_office', 'neutral', name='replyclassification'), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('extracted_intent', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies'))
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    # ### end Alembic commands ###
